package lockfile

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/juanbzz/pensa/internal/index"
	"github.com/juanbzz/pensa/internal/resolve"
	"github.com/juanbzz/pensa/pkg/version"
)

// LockFile represents a parsed or constructed poetry.lock.
type LockFile struct {
	Packages []LockedPackage
	Metadata LockMetadata
}

// LockedPackage represents a single resolved package in the lock file.
type LockedPackage struct {
	Name           string
	Version        string
	Description    string
	Optional       bool
	PythonVersions string
	Groups         []string
	Files          []PackageFile
	Dependencies   map[string]string
	Extras         map[string][]string
}

// PackageFile represents a distribution file entry.
type PackageFile struct {
	File string
	Hash string
}

// LockMetadata contains lock file metadata.
type LockMetadata struct {
	LockVersion    string
	PythonVersions string
	ContentHash    string
}

// WriteLockFile writes a lock file to disk in Poetry's format.
func WriteLockFile(path string, lf *LockFile) error {
	var b strings.Builder

	b.WriteString("# This file is automatically @generated by Pensa and should not be changed by hand.\n\n")

	// Sort packages alphabetically.
	pkgs := make([]LockedPackage, len(lf.Packages))
	copy(pkgs, lf.Packages)
	sort.Slice(pkgs, func(i, j int) bool {
		return pkgs[i].Name < pkgs[j].Name
	})

	for _, pkg := range pkgs {
		b.WriteString("[[package]]\n")
		b.WriteString(fmt.Sprintf("name = %q\n", pkg.Name))
		b.WriteString(fmt.Sprintf("version = %q\n", pkg.Version))
		b.WriteString(fmt.Sprintf("description = %q\n", pkg.Description))
		b.WriteString(fmt.Sprintf("optional = %v\n", pkg.Optional))
		b.WriteString(fmt.Sprintf("python-versions = %q\n", pkg.PythonVersions))

		// Groups.
		b.WriteString("groups = [")
		for i, g := range pkg.Groups {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", g))
		}
		b.WriteString("]\n")

		// Files.
		b.WriteString("files = [\n")
		for _, f := range pkg.Files {
			b.WriteString(fmt.Sprintf("    {file = %q, hash = %q},\n", f.File, f.Hash))
		}
		b.WriteString("]\n")

		// Dependencies.
		if len(pkg.Dependencies) > 0 {
			b.WriteString("\n[package.dependencies]\n")
			depNames := make([]string, 0, len(pkg.Dependencies))
			for name := range pkg.Dependencies {
				depNames = append(depNames, name)
			}
			sort.Strings(depNames)
			for _, name := range depNames {
				b.WriteString(fmt.Sprintf("%s = %q\n", name, pkg.Dependencies[name]))
			}
		}

		// Extras.
		if len(pkg.Extras) > 0 {
			b.WriteString("\n[package.extras]\n")
			extraNames := make([]string, 0, len(pkg.Extras))
			for name := range pkg.Extras {
				extraNames = append(extraNames, name)
			}
			sort.Strings(extraNames)
			for _, name := range extraNames {
				b.WriteString(fmt.Sprintf("%s = [", name))
				for i, dep := range pkg.Extras[name] {
					if i > 0 {
						b.WriteString(", ")
					}
					b.WriteString(fmt.Sprintf("%q", dep))
				}
				b.WriteString("]\n")
			}
		}

		b.WriteString("\n")
	}

	// Metadata.
	b.WriteString("[metadata]\n")
	b.WriteString(fmt.Sprintf("lock-version = %q\n", lf.Metadata.LockVersion))
	b.WriteString(fmt.Sprintf("python-versions = %q\n", lf.Metadata.PythonVersions))
	b.WriteString(fmt.Sprintf("content-hash = %q\n", lf.Metadata.ContentHash))

	return os.WriteFile(path, []byte(b.String()), 0644)
}

// BuildLockFile creates a LockFile from resolver results and package metadata.
// depGroups maps normalized package names to their dependency groups.
// Transitive deps not in depGroups are assigned to "main".
func BuildLockFile(
	result *resolve.SolverResult,
	client *index.PyPIClient,
	pythonVersions string,
	contentHash string,
	depGroups map[string][]string,
) (*LockFile, error) {
	lf := &LockFile{
		Metadata: LockMetadata{
			LockVersion:    "2.1",
			PythonVersions: pythonVersions,
			ContentHash:    contentHash,
		},
	}

	for pkgName, ver := range result.Decisions {
		locked, err := buildLockedPackage(client, pkgName, ver)
		if err != nil {
			return nil, fmt.Errorf("build lock entry for %s: %w", pkgName, err)
		}
		// Assign groups from direct dep mapping; transitive deps get "main".
		normalized := strings.ToLower(strings.ReplaceAll(pkgName, "_", "-"))
		if groups, ok := depGroups[normalized]; ok {
			locked.Groups = groups
		}
		lf.Packages = append(lf.Packages, locked)
	}

	return lf, nil
}

func buildLockedPackage(client *index.PyPIClient, name string, ver version.Version) (LockedPackage, error) {
	detail, err := client.GetVersionDetail(name, ver)
	if err != nil {
		return LockedPackage{}, err
	}

	info, err := client.GetPackageInfo(name)
	if err != nil {
		return LockedPackage{}, err
	}

	pkg := LockedPackage{
		Name:           name,
		Version:        ver.String(),
		Description:    "", // TODO: fetch from JSON API
		Optional:       false,
		PythonVersions: detail.RequiresPython,
		Groups:         []string{"main"},
		Dependencies:   make(map[string]string),
		Extras:         make(map[string][]string),
	}

	// Files.
	for _, f := range info.FilesForVersion(ver) {
		hash := ""
		if sha, ok := f.Hashes["sha256"]; ok {
			hash = "sha256:" + sha
		}
		pkg.Files = append(pkg.Files, PackageFile{
			File: f.Filename,
			Hash: hash,
		})
	}

	// Dependencies (non-extra only).
	for _, dep := range detail.Dependencies {
		if dep.Markers != nil {
			// Check if it's an extras-only dep.
			markerStr := dep.Markers.String()
			if strings.Contains(markerStr, "extra ==") || strings.Contains(markerStr, "extra ==") {
				// This is an extras dependency, categorize it.
				// Simple heuristic: extract extra name from marker.
				continue
			}
		}
		if dep.Constraint != nil {
			pkg.Dependencies[dep.Name] = dep.Constraint.String()
		}
	}

	return pkg, nil
}
