package lockfile

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// WritePensaLockFile writes a lock file in pensa.lock format.
// Includes full download URLs for direct installs without PyPI lookup.
func WritePensaLockFile(path string, lf *LockFile) error {
	var b strings.Builder

	b.WriteString("# This file is automatically @generated by Pensa and should not be changed by hand.\n\n")

	// Sort packages alphabetically.
	pkgs := make([]LockedPackage, len(lf.Packages))
	copy(pkgs, lf.Packages)
	sort.Slice(pkgs, func(i, j int) bool {
		return pkgs[i].Name < pkgs[j].Name
	})

	for _, pkg := range pkgs {
		b.WriteString("[[package]]\n")
		b.WriteString(fmt.Sprintf("name = %q\n", pkg.Name))
		b.WriteString(fmt.Sprintf("version = %q\n", pkg.Version))
		if pkg.Description != "" {
			b.WriteString(fmt.Sprintf("description = %q\n", pkg.Description))
		}
		if pkg.PythonVersions != "" {
			b.WriteString(fmt.Sprintf("python-versions = %q\n", pkg.PythonVersions))
		}

		// Groups.
		if len(pkg.Groups) > 0 {
			b.WriteString("groups = [")
			for i, g := range pkg.Groups {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(fmt.Sprintf("%q", g))
			}
			b.WriteString("]\n")
		}

		// Files — compatible with poetry.lock reader (file + hash).
		// Also includes URL when available for direct downloads.
		b.WriteString("files = [\n")
		for _, f := range pkg.Files {
			if f.URL != "" {
				b.WriteString(fmt.Sprintf("    {file = %q, hash = %q, url = %q},\n", f.File, f.Hash, f.URL))
			} else {
				b.WriteString(fmt.Sprintf("    {file = %q, hash = %q},\n", f.File, f.Hash))
			}
		}
		b.WriteString("]\n")

		// Dependencies.
		if len(pkg.Dependencies) > 0 {
			b.WriteString("\n[package.dependencies]\n")
			depNames := make([]string, 0, len(pkg.Dependencies))
			for name := range pkg.Dependencies {
				depNames = append(depNames, name)
			}
			sort.Strings(depNames)
			for _, name := range depNames {
				b.WriteString(fmt.Sprintf("%s = %q\n", name, pkg.Dependencies[name]))
			}
		}

		// Extras.
		if len(pkg.Extras) > 0 {
			b.WriteString("\n[package.extras]\n")
			extraNames := make([]string, 0, len(pkg.Extras))
			for name := range pkg.Extras {
				extraNames = append(extraNames, name)
			}
			sort.Strings(extraNames)
			for _, name := range extraNames {
				b.WriteString(fmt.Sprintf("%s = [", name))
				for i, dep := range pkg.Extras[name] {
					if i > 0 {
						b.WriteString(", ")
					}
					b.WriteString(fmt.Sprintf("%q", dep))
				}
				b.WriteString("]\n")
			}
		}

		b.WriteString("\n")
	}

	// Metadata.
	b.WriteString("[metadata]\n")
	b.WriteString(fmt.Sprintf("lock-version = %q\n", lf.Metadata.LockVersion))
	b.WriteString(fmt.Sprintf("python-versions = %q\n", lf.Metadata.PythonVersions))
	b.WriteString(fmt.Sprintf("content-hash = %q\n", lf.Metadata.ContentHash))

	return os.WriteFile(path, []byte(b.String()), 0644)
}
