when:
  - event: push
    branch: main
  - event: manual
    branch: main

steps:
  build:
    image: hugomods/hugo:exts-0.159.0
    commands:
      - cd docs
      - hugo mod get -u
      - hugo --minify --gc

  deploy:
    image: node:20-alpine
    environment:
      CLOUDFLARE_API_TOKEN:
        from_secret: cloudflare_api_token
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: cloudflare_account_id
    commands:
      - npm install -g wrangler@latest
      - wrangler pages deploy docs/public --project-name=pensa --branch=main --commit-dirty=true
